---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./coredns.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./rook-ceph.yaml
  - ./hajimari-charts.yaml
  - ./grafana.yaml
  - ./cloudnative-pg.yaml
  - ./csi-driver-nfs.yaml
  - ./nextcloud.yaml
  - ./authentik.yaml
